services:
  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    command: |
      sh -c "
        uv pip install --system -e . && \
        uvicorn api.app:app --host 0.0.0.0 --port 8888 --reload
      "
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
