model:
  hidden_size: 512
  n_harmonic: 64
  n_bands: 65
  sampling_rate: 16000 # must be same as preprocess.sampling_rate
  block_size: 512 # must be same as preprocess.block_size

train:
  data_dir: pretrain_dataset/
  statistics_dir: pretrain_dataset/statistics/
  batch_size: 16
  epochs: 3000
  lr: 1e-3
  debug: true

loss:
  - type: "mel"
    ratio: 0.5
    scales: [4096,2048, 1024, 512, 256, 128]
    overlap: .75
  # type: "td"
  #   ratio: 0.5
  #   target: "loudness"
  #   alpha: 
  # type: "fd"
  #   target: "pitch"
  #   ratio: 0.5
